FROM mcr.microsoft.com/devcontainers/javascript-node:0-${templateOption:imageVariant}

# [Optional] Uncomment this section to install additional OS packages.
# RUN apt-get update && export DEBIAN_FRONTEND=noninteracti