name: "Update Documentation"
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    environment: documentation
    if: "github.ref == 'refs/heads/main'"
    steps:
      - uses: actions/checkout@v3

      - name: Generate Documentation
        uses: devcontainers/action@v1
        with:
          generate-docs: "true"
          base-path-to-templates: "./src"

      - name: Create a PR for Documentation
        id: push_image_info
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        run: |
          set -e
          echo "Start."

          # Configure git and Push updates
          git config --global user.email github-actions@github.com
 