name: "Update Documentation"
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    environment: documentation
    if: "github.ref == 'refs/heads/main'"
    steps:
      - uses: actions/checkout@v3

      - name: Generate Documentation
        uses: devcontainers/action@v1
        with:
          generate-docs: "true"
          b